#!/bin/bash


if [ $1 == "-t" ]
then
	for file in utests/*.py
	do
		python3 $file
	done
else
	if [ ! -f src/parser/db/db-symbol ]
	then
		sh init.sh
	fi
	python3 src/view.py
fi



#python3 src/view.py
